### ISSUE TITLE
Version for 0.0.25?

### ISSUE THREAD

**Issue by sl5net** [badosu/badmod#3]
i updated the mod.json
    "dependencies": ["0ad=0.0.25"],
now it starts but crashes later?
is somewhere a newer version? ty

**Comment by sl5net** [comment]
maybe set a hint in your readme to use feldMap. seems many use it https://wildfiregames.com/forum/topic/53880-feldmap-a25/

**Comment by badosu** [comment]
Done, thanks!

**Comment by andy5995** [comment]
btw, the maps from feldmap are included with [community maps 2](https://github.com/0ad-matters/community-maps-2), which can be downloaded from the 0ad mod center.

**Comment by badosu** [comment]
Yeah no slopes tho, that together with wrench are the only really interesting things to pull from this project

**Comment by andy5995** [comment]
There's also https://github.com/0ad-matters/balanced_maps_2 I think the main problems are that just a few of the biomes don't work.

**Comment by badosu** [comment]
Yep, need to fix place food for different biomes. And new flora too, etc. Not a huge deal, but boring work

**Comment by badosu** [comment]
Thanks for highlighting, will use your version
